const route = (method, path, options = {}) => Object.freeze({
  method,
  path,
  parameters: Object.freeze(options.parameters ?? []),
  query: Object.freeze(options.query ?? []),
  requiresStateGuard: options.requiresStateGuard ?? false,
  authorization: options.authorization ?? 'host-only',
});

const shape = (name, fields, source) => Object.freeze({
  name,
  fields: Object.freeze(fields),
  source,
});

export const currentContract = Object.freeze({
  classification: 'CURRENT',
  applicationVersion: '0.10.12',
  implementation: Object.freeze({
    runtime: 'Bun',
    server: 'server.mjs',
    frontend: 'vendored React SPA under app/',
    bind: Object.freeze({ host: '127.0.0.1', port: 47832 }),
    persistence: Object.freeze({ engine: 'SQLite', journalMode: 'WAL', schemaVersion: 7 }),
    nativeCore: 'native/core is a Rust contract/scaffold, not the production WASAPI implementation',
  }),
  authentication: Object.freeze({
    tokenIssuedBy: 'GET /v1/bootstrap',
    tokenHeader: 'x-auralis-token',
    tokenLifetime: 'one server process',
    tokenStorage: 'application memory only',
    hostCheck: 'all requests require Host 127.0.0.1:47832 or localhost:47832',
    sameOriginCheck: 'bootstrap and state-changing routes reject non-local Origin values',
    diagnosticsQuirk: 'GET /v1/diagnostics/export checks only the process token after the global Host check',
  }),
  credentials: Object.freeze({
    suppliedAtRuntime: true,
    retainedInMemoryOnly: true,
    persistedToLocalStorage: false,
    persistedToSQLite: false,
    logged: false,
    statusResponsesAreRedacted: true,
  }),
  realtime: Object.freeze({
    transport: 'HTTP polling',
    eventSource: 'persisted SQLite event_log',
    uiPollingIntervalsMs: Object.freeze({ main: 1000, metrics: 5000 }),
    overlappingMainPolls: false,
    websocket: false,
    serverSentEvents: false,
  }),
  quirks: Object.freeze({
    healthStatus: 'degraded',
    diagnosticsAuthorization: 'Host plus x-auralis-token; no same-Origin check',
    activityDelivery: 'polling a redacted view of persisted event_log rows',
  }),
  routes: Object.freeze([
    route('GET', '/v1/bootstrap', { authorization: 'host-and-same-origin' }),
    route('GET', '/v1/health'),
    route('GET', '/v1/metrics/summary'),
    route('GET', '/v1/native-capture/status'),
    route('POST', '/v1/native-capture/start', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/native-capture/stop', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('GET', '/v1/audio/chunks', { query: ['sessionId'] }),
    route('GET', '/v1/asr/status'),
    route('POST', '/v1/asr/config', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/runtime/quick-setup', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/brain/runtime-config', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/segments/{segmentId}/retranscribe', { parameters: ['segmentId'], requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/asr/retry-failed', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/router/classify', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('GET', '/v1/sessions', { query: ['limit'] }),
    route('POST', '/v1/sessions', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('GET', '/v1/sessions/{sessionId}', { parameters: ['sessionId'] }),
    route('PATCH', '/v1/sessions/{sessionId}', { parameters: ['sessionId'], requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/sessions/{sessionId}/stop', { parameters: ['sessionId'], requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('GET', '/v1/sessions/{sessionId}/turns', { parameters: ['sessionId'] }),
    route('GET', '/v1/sessions/{sessionId}/transcripts', { parameters: ['sessionId'], query: ['limit'] }),
    route('GET', '/v1/sessions/{sessionId}/gaps', { parameters: ['sessionId'] }),
    route('GET', '/v1/sessions/{sessionId}/activity', { parameters: ['sessionId'], query: ['limit'] }),
    route('POST', '/v1/questions', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('GET', '/v1/turns/{turnId}', { parameters: ['turnId'] }),
    route('POST', '/v1/turns/{turnId}/answer', { parameters: ['turnId'], requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/brain/test', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('GET', '/v1/sources'),
    route('POST', '/v1/sources', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('DELETE', '/v1/sources/{sourceId}', { parameters: ['sourceId'], requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('POST', '/v1/retrieve', { requiresStateGuard: true, authorization: 'host-origin-token' }),
    route('GET', '/v1/diagnostics/export', { authorization: 'host-and-token' }),
    route('POST', '/v1/shutdown', { requiresStateGuard: true, authorization: 'host-origin-token' }),
  ]),
  eventLog: Object.freeze({
    schemaVersion: 1,
    envelopeFields: Object.freeze(['id', 'schema_version', 'event_type', 'session_id', 'correlation_id', 'payload', 'occurred_at']),
    dynamicTypeRule: 'Every native probe type except probe.heartbeat is persisted as native.<probeEvent.type>',
    emittedTypes: Object.freeze([
      'answer.auto_error',
      'answer.completed',
      'answer.failed',
      'answer.policy_skipped',
      'answer.queued',
      'asr.config_changed',
      'asr.failed',
      'asr.replay_error',
      'asr.replay_queued',
      'asr.retry_drain_error',
      'asr.retry_scheduled',
      'asr.started',
      'asr.worker_error',
      'brain.runtime_config_changed',
      'native.audio.chunk_closed',
      'native.audio.chunk_recovered',
      'native.audio.gap_detected',
      'native.capture.channel_failed',
      'native.capture.channel_started',
      'native.capture.channel_stopped',
      'native.capture.format_unsupported',
      'native.probe_parse_error',
      'native.probe_stderr',
      'native.segment.frozen',
      'native.vad.decode_failed',
      'native.vad.level',
      'native.vad.speech_started',
      'provider.http_error',
      'provider.network_error',
      'provider.schema_error',
      'retrieval.failed',
      'runtime.quick_setup',
      'segment.frozen.persisted',
      'session.closed',
      'session.settings_updated',
      'session.started',
      'source.indexed',
      'transcript.empty',
      'transcript.final',
      'turn.committed',
      'turn.transcript_revised',
    ]),
    activityResponseFields: Object.freeze(['id', 'eventType', 'sessionId', 'correlationId', 'payload', 'occurredAt']),
    activityAllowedPayloadKeys: Object.freeze(['mode', 'state', 'turn_id', 'segment_id', 'ordinal', 'kind', 'source_role', 'provider', 'model', 'attempt', 'error', 'retry_in_seconds', 'grounding', 'chunks', 'channel_id']),
  }),
  shapes: Object.freeze([
    shape('BootstrapResponse', ['token', 'version', 'schemaVersion', 'releaseClass'], 'GET /v1/bootstrap'),
    shape('HealthResponse', ['product', 'version', 'releaseClass', 'status', 'reason', 'schemaVersion', 'components', 'capabilities', 'nonCapabilities'], 'GET /v1/health'),
    shape('RuntimeStatus', ['enabled', 'provider', 'model', 'projectId', 'location', 'language', 'autoCommitTurns', 'hasCredential', 'lastState', 'lastError', 'lastSuccessAt'], 'GET /v1/asr/status'),
    shape('BrainRuntimeStatus', ['enabled', 'autoAnswer', 'model', 'strictSource', 'hasCredential', 'lastState', 'lastError', 'lastSuccessAt'], 'metrics and runtime configuration responses'),
    shape('SessionListResponse', ['sessions', 'activeSessionId', 'captureState'], 'GET /v1/sessions'),
    shape('Session', ['id', 'started_at', 'ended_at', 'mode', 'state', 'context_text', 'response_style'], 'sessions table and session endpoints'),
    shape('SessionSummary', ['id', 'started_at', 'ended_at', 'mode', 'state', 'context_text', 'response_style', 'turn_count', 'segment_count', 'gap_count', 'audio_chunk_count'], 'GET /v1/sessions'),
    shape('Turn', ['id', 'session_id', 'ordinal', 'source_role', 'kind', 'text_raw', 'text_normalized', 'route_reason', 'route_score', 'client_request_id', 'state', 'created_at'], 'turns table and turn endpoints'),
    shape('TurnSummary', ['id', 'session_id', 'ordinal', 'source_role', 'kind', 'text_raw', 'text_normalized', 'route_reason', 'route_score', 'client_request_id', 'state', 'created_at', 'answer_id', 'answer_text', 'answer_grounding', 'answer_created_at'], 'GET /v1/sessions/{sessionId}/turns'),
    shape('Answer', ['answerId', 'turnId', 'lane', 'model', 'answer', 'grounding', 'sourceChunkIds', 'retrieved', 'invalidCitationCount', 'createdAt'], 'answerFromRow and turn detail/answer responses'),
    shape('AnswerEnvelope', ['answer', 'sourceChunkIds', 'grounding', 'invalidCitationCount', 'schemaVersion'], 'core/answer-schema.mjs'),
    shape('TurnDetailResponse', ['turn', 'answers', 'latestAnswer', 'segments'], 'GET /v1/turns/{turnId}'),
    shape('QuestionResponse', ['turn', 'route'], 'POST /v1/questions; deduplicated is additionally present on replay'),
    shape('AnswerResponse', ['result', 'turn', 'correlationId', 'deduplicated'], 'POST /v1/turns/{turnId}/answer; correlationId is absent on idempotent replay'),
    shape('RouteClassification', ['normalized', 'shouldAnswer', 'kind', 'reason', 'score', 'mode'], 'core/persian-router.mjs'),
    shape('RetrievalResult', ['chunkId', 'documentId', 'title', 'ordinal', 'score', 'startOffset', 'endOffset', 'excerpt'], 'POST /v1/retrieve and Answer.retrieved'),
    shape('ActivityEvent', ['id', 'eventType', 'sessionId', 'correlationId', 'payload', 'occurredAt'], 'GET /v1/sessions/{sessionId}/activity'),
    shape('TranscriptTimelineItem', ['segment_id', 'session_id', 'channel_id', 'seq_start', 'seq_end', 'duration_ms', 'endpoint_reason', 'vad_engine', 'segment_state', 'created_at', 'transcript_revision_id', 'revision', 'provider', 'provider_model', 'text_raw', 'text_normalized', 'is_final', 'transcript_created_at', 'asr_status', 'asr_attempt', 'asr_error', 'asr_provider_status', 'asr_available_at', 'asr_retry_after_seconds'], 'GET /v1/sessions/{sessionId}/transcripts'),
  ]),
});
